# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# Set deep sleep to 15 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_PM_SOFT_OFF=y

# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Change board name
CONFIG_ZMK_KEYBOARD_NAME="Yan Pelletier"

# Allows mouse scrolling 
CONFIG_ZMK_POINTING=y

# Debounce — Choc switches for high speed typing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5