manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: YanPelletier
      url-base: https://github.com/YanPelletier
    - name: infely
      url-base: https://github.com/infely
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-ecaps-word
      remote: YanPelletier
      revision: main
      path: modules/ecaps-word
    - name: nice-view-battery
      remote: infely
      revision: main
  self:
    path: config